apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "zookeeper.name" . }}
  namespace: {{ template "zookeeper.name" . }}-{{ .Values.global.environmentName }}
data:
  tick: {{ .Values.zookeeperTick | quote }}
  servers: "{{ template "zookeeper.name" . }}-0.{{ template "zookeeper.name" . }}.{{ template "zookeeper.name" . }}-{{ .Values.global.environmentName }}.svc.cluster.local:2888:3888;{{ template "zookeeper.name" . }}-1.{{ template "zookeeper.name" . }}.{{ template "zookeeper.name" . }}-{{ .Values.global.environmentName }}.svc.cluster.local:2888:3888;{{ template "zookeeper.name" . }}-2.{{ template "zookeeper.name" . }}.{{ template "zookeeper.name" . }}-{{ .Values.global.environmentName }}.svc.cluster.local:2888:3888"
