apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.name" . }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ template "zookeeper.name" . }}-{{ .Values.global.environmentName }}
spec:
  ports:
  - port: 2181
    name: clients
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
